---
title: "Your Document Title"
author: "Document Author"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(prompt=TRUE,
                      comment="➤",
                      results='hold',
                      warning=FALSE,
                      dpi=300)
```


```{r}
#实现cos(x) = x 的根的近似(大于0 的那个就行)
t1=proc.time()
a=0
b=pi/2
k=(a+b)/2
f=function(x)
{
  y=cos(x)-x
  return(y)
}
#while循环 只要满足小括号的条件 就一直运行
#for 自动每个循环有个值啊 这个没有

while(abs(f(k))>0.0001)
{
  
  if(f(a)*f(k)<0)
  {
    b=k
    k=(a+b)/2
  }
  #else#这个else包括了f(a)*f(k)>0
    #然而，f(a)*f(k)<0的对立集合，并不是f(b)*f(k)<0
  if(f(b)*f(k)<0)
  {
    a=k
    k=(a+b)/2
  }
  
}

t2=proc.time()
t=t2-t1
cat(k,t[3][[1]])
```
```{r}
#给你5分钟 计算斐波那契数列10项和第11项之比
a=1
b=1
i=2
while(i<10)
{
  a=a+b #第10-1项
  b=a+b #第10项
  i=i+2
}
cat(a,b)
```
```{r}
a = vector()
a[1] = 1
a[2] = 1

i = 1
while (i<100) {
  a[i+2] = a[i+1]+a[i]
  i = i+1
}
```


```{r}
plot.ts(log(a))
abline(a = 1,b=0.48)
```
```{r}
e^(0.48*80)-a[81]

```
```{r}
A = matrix(c(100,140,60,80,50,30,-20,-40,10),nrow = 3)
B = matrix(c(0.3,0.5,0.2),nrow=3)
A%*%B
```
```{r}
cout = vector()
for (j in 1:10000) {
  i = 0
  a = 0
  while (a == 0) {
    i=i+1
    a = a+rbinom(1,1,0.5)
  }
  cout[j] = i
}

```

```{r}
success <- 0:385

plot(success, dbinom(success, size=385, prob=a),type='h',xlim = c(0,10))
```

```{r}
phi = sin(104*pi/180)/6381
y = sin(76*pi/180-asin(6371*phi))/phi

```
```{r}
e= 2.718281828
a = 5.41011*e^(-0.138629)
b = 21.6404*e^(-0.0346574)
```

```{r}
n = 30
v = vector()
for (i in 0:n) {
  v[i+1] = choose(n,i)
}
plot.ts(v)
```

```{r}
cumsum(sample(c(-1,1),10,replace=TRUE))
```


```{r}
wuhu = function(M){
  K = 9-M
  times = vector()
for (m in 1:5000) {
L = rep(-1,K)
i=0
while(sum(L)<K)
  {
    i = i+1
    S = sample(c(1:3),1)
    Loc = sample(c(1:K),S)
    for (j in 1:S) {
      L[Loc[j]] = L[Loc[j]]*(-1)
    }
}
  times[m]=i
}
 return(times)
}
```

```{r}
start <- Sys.time()
ts = vector()
for (l in 0:6) {
  ts[l+1] = mean(wuhu(l))
}
end <- Sys.time()
end-start

```
```{r}
#plot.ts(ts)
lam = 1/520

hist(Data11,breaks=300,freq=FALSE,xlim = c(0,5000),ylim = c(0,0.0020),col = "pink",border = NA)
curve(lam*e^(-lam*x),add=TRUE,col="#401F12")
```
```{r}
kk = vector()
i=0
for (x in 10:2000) {
  i=i+1
  y=1-e^(-lam*x)
  ss = sum(Data11<x)/length(Data11)
  kk[i]= y-ss
}
```

```{r}
x = 600
 y=1-e^(-lam*x)
 ss = sum(Data11<x)/length(Data11)
```

```{r}
wuhu2 = function(M){
  K = 9-M
  times = vector()
for (m in 1:3000) {
L = c(1,1,1,1,1,1,1,1,-1)
i=0
while(sum(L)<K)
  {
    i = i+1
    S = sample(c(1:3),1)
    Loc = sample(c(1:K),S)
    for (j in 1:S) {
      L[Loc[j]] = L[Loc[j]]*(-1)
    }
}
  times[m]=i
}
 return(times)
}
```

```{r}
start <- Sys.time()
ts = vector()
for (l in 0:6) {
  ts[l+1] = mean(wuhu2(l))
}
end <- Sys.time()
end-start

```
```{r}
#plot.ts(ts)
lam = 1/520

hist(Data11,breaks=300,freq=FALSE,xlim = c(0,5000),ylim = c(0,0.0020),col = "pink",border = NA)
curve(lam*e^(-lam*x),add=TRUE,col="blue")
```

```{r}
c=1
d = b+1
for (i in 1:4) {
  c=d[i]*c
}
c^0.25-1


```

```{r}
a = vector()
a[1] = 1
a[2] = 0.8
for (i in 1:30) {
  a[i+2] = 1.6*a[i+1]-0.9*a[i]
}
```

```{r}
weighted_interval_sample = function(interval,weight){
  sum_weight = sum(weight)
  re_weight = c()
  for (j in 1:length(weight)) {
    re_weight[j] = weight[j]/sum_weight
  }
  len = length(interval)
  l_wei = length(re_weight)
  if (len%% 2 == 0 & all(weight>0) & l_wei==len/2) {
    rand = runif(1)
    i = 1
    swei = re_weight[i]
    a = 0
    while (a==0) {
      if (rand<=swei) {
        a = runif(1,interval[2*i-1],interval[2*i])
      }
      else{swei = swei+weight[i+1]
      i=i+1}
    }
    
  }
  return(a)
}
```

```{r}
wuhu = c()
for (k in 1:1000) {
  wuhu[k] = weighted_interval_sample(c(1,2,3,4),c(20,20))
}
```

```{r}
text <- c("apple", "banana", "cherry", "date")
pattern <- "an"
result <- grep(pattern, text, value = TRUE)
print(result)
```

```{r}
m = function(data,nr,nc)
  {
    return(matrix(data,nr,nc))
}

mm = function(matrixA,matrixB)
  {
    return(matrixA %*% matrixB)
}

am = function(matrixA)
  {
    return(solve(matrixA)*det(matrixA))
  }
```

```{r}
#副对角线的行列式
a = c()
for (i in 1:20) {
  a[i] = (-1)^(i*(i-1)/2)
}
```



 
```{r}
a = m(c(0,0,1,0,1,0,2,0,0),3,3)

```

```{r}
Ma = c(1:4)
Mb = rep(1,4)
Mc = c(1:3,2)
Md = Ma+Mb+Mc
Mat_A = rbind(Ma,Mb,Mc,Md)
```

```{r}
a = m(c(1,0,1,0),2,2)
b = m(c(1,0,0,1),2,2)
c = m(c(1,1,1,0),2,2)
d = m(c(0,1,1,0),2,2)
e = m(c(0,0,1,1),2,2)
```
```{r}
a = m(c(2,4,0,-1,-3,0,5,5,-2),3,3)
b = m(c(1,-1,-1,-2,-3,1,1,1,0),3,3)
c = m(c(1,4,0,0,5,1,1,1,0),3,3)
lambda = diag(c(-2,-2,1),3,3)
b_i = solve(b)
c_i = solve(c)
```

```{r}
a%*%b
b%*%lambda

```


